/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as OnboardingSuccessRouteImport } from './routes/onboarding_.success'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as DashboardAdminRouteRouteImport } from './routes/dashboard/admin/route'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as DashboardAdminMembersRouteImport } from './routes/dashboard/admin/members'
import { Route as DashboardAdminTemplatesIndexRouteImport } from './routes/dashboard/admin/templates/index'
import { Route as DashboardAdminSalonsIndexRouteImport } from './routes/dashboard/admin/salons/index'
import { Route as DashboardAdminTemplatesTemplateIdRouteImport } from './routes/dashboard/admin/templates/$templateId'
import { Route as DashboardAdminSalonsSalonIdRouteImport } from './routes/dashboard/admin/salons/$salonId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const OnboardingSuccessRoute = OnboardingSuccessRouteImport.update({
  id: '/onboarding_/success',
  path: '/onboarding/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRouteRoute = DashboardAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const DashboardAdminMembersRoute = DashboardAdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const DashboardAdminTemplatesIndexRoute =
  DashboardAdminTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const DashboardAdminSalonsIndexRoute =
  DashboardAdminSalonsIndexRouteImport.update({
    id: '/salons/',
    path: '/salons/',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const DashboardAdminTemplatesTemplateIdRoute =
  DashboardAdminTemplatesTemplateIdRouteImport.update({
    id: '/templates/$templateId',
    path: '/templates/$templateId',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const DashboardAdminSalonsSalonIdRoute =
  DashboardAdminSalonsSalonIdRouteImport.update({
    id: '/salons/$salonId',
    path: '/salons/$salonId',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/members': typeof DashboardAdminMembersRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/admin/salons/$salonId': typeof DashboardAdminSalonsSalonIdRoute
  '/dashboard/admin/templates/$templateId': typeof DashboardAdminTemplatesTemplateIdRoute
  '/dashboard/admin/salons/': typeof DashboardAdminSalonsIndexRoute
  '/dashboard/admin/templates/': typeof DashboardAdminTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/members': typeof DashboardAdminMembersRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/admin/salons/$salonId': typeof DashboardAdminSalonsSalonIdRoute
  '/dashboard/admin/templates/$templateId': typeof DashboardAdminTemplatesTemplateIdRoute
  '/dashboard/admin/salons': typeof DashboardAdminSalonsIndexRoute
  '/dashboard/admin/templates': typeof DashboardAdminTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/onboarding_/success': typeof OnboardingSuccessRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/members': typeof DashboardAdminMembersRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/admin/salons/$salonId': typeof DashboardAdminSalonsSalonIdRoute
  '/dashboard/admin/templates/$templateId': typeof DashboardAdminTemplatesTemplateIdRoute
  '/dashboard/admin/salons/': typeof DashboardAdminSalonsIndexRoute
  '/dashboard/admin/templates/': typeof DashboardAdminTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/dashboard/admin'
    | '/auth/callback'
    | '/onboarding/success'
    | '/dashboard/'
    | '/dashboard/admin/members'
    | '/dashboard/admin/'
    | '/dashboard/admin/salons/$salonId'
    | '/dashboard/admin/templates/$templateId'
    | '/dashboard/admin/salons/'
    | '/dashboard/admin/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/auth/callback'
    | '/onboarding/success'
    | '/dashboard'
    | '/dashboard/admin/members'
    | '/dashboard/admin'
    | '/dashboard/admin/salons/$salonId'
    | '/dashboard/admin/templates/$templateId'
    | '/dashboard/admin/salons'
    | '/dashboard/admin/templates'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/dashboard/admin'
    | '/auth/callback'
    | '/onboarding_/success'
    | '/dashboard/'
    | '/dashboard/admin/members'
    | '/dashboard/admin/'
    | '/dashboard/admin/salons/$salonId'
    | '/dashboard/admin/templates/$templateId'
    | '/dashboard/admin/salons/'
    | '/dashboard/admin/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  OnboardingSuccessRoute: typeof OnboardingSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/onboarding_/success': {
      id: '/onboarding_/success'
      path: '/onboarding/success'
      fullPath: '/onboarding/success'
      preLoaderRoute: typeof OnboardingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/members': {
      id: '/dashboard/admin/members'
      path: '/members'
      fullPath: '/dashboard/admin/members'
      preLoaderRoute: typeof DashboardAdminMembersRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/templates/': {
      id: '/dashboard/admin/templates/'
      path: '/templates'
      fullPath: '/dashboard/admin/templates/'
      preLoaderRoute: typeof DashboardAdminTemplatesIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/salons/': {
      id: '/dashboard/admin/salons/'
      path: '/salons'
      fullPath: '/dashboard/admin/salons/'
      preLoaderRoute: typeof DashboardAdminSalonsIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/templates/$templateId': {
      id: '/dashboard/admin/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/dashboard/admin/templates/$templateId'
      preLoaderRoute: typeof DashboardAdminTemplatesTemplateIdRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/salons/$salonId': {
      id: '/dashboard/admin/salons/$salonId'
      path: '/salons/$salonId'
      fullPath: '/dashboard/admin/salons/$salonId'
      preLoaderRoute: typeof DashboardAdminSalonsSalonIdRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
  }
}

interface DashboardAdminRouteRouteChildren {
  DashboardAdminMembersRoute: typeof DashboardAdminMembersRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
  DashboardAdminSalonsSalonIdRoute: typeof DashboardAdminSalonsSalonIdRoute
  DashboardAdminTemplatesTemplateIdRoute: typeof DashboardAdminTemplatesTemplateIdRoute
  DashboardAdminSalonsIndexRoute: typeof DashboardAdminSalonsIndexRoute
  DashboardAdminTemplatesIndexRoute: typeof DashboardAdminTemplatesIndexRoute
}

const DashboardAdminRouteRouteChildren: DashboardAdminRouteRouteChildren = {
  DashboardAdminMembersRoute: DashboardAdminMembersRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
  DashboardAdminSalonsSalonIdRoute: DashboardAdminSalonsSalonIdRoute,
  DashboardAdminTemplatesTemplateIdRoute:
    DashboardAdminTemplatesTemplateIdRoute,
  DashboardAdminSalonsIndexRoute: DashboardAdminSalonsIndexRoute,
  DashboardAdminTemplatesIndexRoute: DashboardAdminTemplatesIndexRoute,
}

const DashboardAdminRouteRouteWithChildren =
  DashboardAdminRouteRoute._addFileChildren(DashboardAdminRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAdminRouteRoute: typeof DashboardAdminRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAdminRouteRoute: DashboardAdminRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  OnboardingSuccessRoute: OnboardingSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
