/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as OnboardingSuccessRouteImport } from './routes/onboarding_.success'
import { Route as DashboardSubmissionsRouteImport } from './routes/dashboard/submissions'
import { Route as DashboardMembersRouteImport } from './routes/dashboard/members'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as DashboardTemplatesIndexRouteImport } from './routes/dashboard/templates/index'
import { Route as DashboardSalonsIndexRouteImport } from './routes/dashboard/salons/index'
import { Route as DashboardTemplatesTemplateIdRouteImport } from './routes/dashboard/templates/$templateId'
import { Route as DashboardSalonsSalonIdRouteImport } from './routes/dashboard/salons/$salonId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const OnboardingSuccessRoute = OnboardingSuccessRouteImport.update({
  id: '/onboarding_/success',
  path: '/onboarding/success',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSubmissionsRoute = DashboardSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardMembersRoute = DashboardMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTemplatesIndexRoute = DashboardTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSalonsIndexRoute = DashboardSalonsIndexRouteImport.update({
  id: '/salons/',
  path: '/salons/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTemplatesTemplateIdRoute =
  DashboardTemplatesTemplateIdRouteImport.update({
    id: '/templates/$templateId',
    path: '/templates/$templateId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardSalonsSalonIdRoute = DashboardSalonsSalonIdRouteImport.update({
  id: '/salons/$salonId',
  path: '/salons/$salonId',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/submissions': typeof DashboardSubmissionsRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/salons/$salonId': typeof DashboardSalonsSalonIdRoute
  '/dashboard/templates/$templateId': typeof DashboardTemplatesTemplateIdRoute
  '/dashboard/salons/': typeof DashboardSalonsIndexRoute
  '/dashboard/templates/': typeof DashboardTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/submissions': typeof DashboardSubmissionsRoute
  '/onboarding/success': typeof OnboardingSuccessRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/salons/$salonId': typeof DashboardSalonsSalonIdRoute
  '/dashboard/templates/$templateId': typeof DashboardTemplatesTemplateIdRoute
  '/dashboard/salons': typeof DashboardSalonsIndexRoute
  '/dashboard/templates': typeof DashboardTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/members': typeof DashboardMembersRoute
  '/dashboard/submissions': typeof DashboardSubmissionsRoute
  '/onboarding_/success': typeof OnboardingSuccessRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/salons/$salonId': typeof DashboardSalonsSalonIdRoute
  '/dashboard/templates/$templateId': typeof DashboardTemplatesTemplateIdRoute
  '/dashboard/salons/': typeof DashboardSalonsIndexRoute
  '/dashboard/templates/': typeof DashboardTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/auth/callback'
    | '/dashboard/admin'
    | '/dashboard/members'
    | '/dashboard/submissions'
    | '/onboarding/success'
    | '/dashboard/'
    | '/dashboard/salons/$salonId'
    | '/dashboard/templates/$templateId'
    | '/dashboard/salons/'
    | '/dashboard/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/auth/callback'
    | '/dashboard/admin'
    | '/dashboard/members'
    | '/dashboard/submissions'
    | '/onboarding/success'
    | '/dashboard'
    | '/dashboard/salons/$salonId'
    | '/dashboard/templates/$templateId'
    | '/dashboard/salons'
    | '/dashboard/templates'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/onboarding'
    | '/auth/callback'
    | '/dashboard/admin'
    | '/dashboard/members'
    | '/dashboard/submissions'
    | '/onboarding_/success'
    | '/dashboard/'
    | '/dashboard/salons/$salonId'
    | '/dashboard/templates/$templateId'
    | '/dashboard/salons/'
    | '/dashboard/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  OnboardingSuccessRoute: typeof OnboardingSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/onboarding_/success': {
      id: '/onboarding_/success'
      path: '/onboarding/success'
      fullPath: '/onboarding/success'
      preLoaderRoute: typeof OnboardingSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/submissions': {
      id: '/dashboard/submissions'
      path: '/submissions'
      fullPath: '/dashboard/submissions'
      preLoaderRoute: typeof DashboardSubmissionsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/members': {
      id: '/dashboard/members'
      path: '/members'
      fullPath: '/dashboard/members'
      preLoaderRoute: typeof DashboardMembersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/templates/': {
      id: '/dashboard/templates/'
      path: '/templates'
      fullPath: '/dashboard/templates/'
      preLoaderRoute: typeof DashboardTemplatesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/salons/': {
      id: '/dashboard/salons/'
      path: '/salons'
      fullPath: '/dashboard/salons/'
      preLoaderRoute: typeof DashboardSalonsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/templates/$templateId': {
      id: '/dashboard/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/dashboard/templates/$templateId'
      preLoaderRoute: typeof DashboardTemplatesTemplateIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/salons/$salonId': {
      id: '/dashboard/salons/$salonId'
      path: '/salons/$salonId'
      fullPath: '/dashboard/salons/$salonId'
      preLoaderRoute: typeof DashboardSalonsSalonIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardMembersRoute: typeof DashboardMembersRoute
  DashboardSubmissionsRoute: typeof DashboardSubmissionsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSalonsSalonIdRoute: typeof DashboardSalonsSalonIdRoute
  DashboardTemplatesTemplateIdRoute: typeof DashboardTemplatesTemplateIdRoute
  DashboardSalonsIndexRoute: typeof DashboardSalonsIndexRoute
  DashboardTemplatesIndexRoute: typeof DashboardTemplatesIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardMembersRoute: DashboardMembersRoute,
  DashboardSubmissionsRoute: DashboardSubmissionsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSalonsSalonIdRoute: DashboardSalonsSalonIdRoute,
  DashboardTemplatesTemplateIdRoute: DashboardTemplatesTemplateIdRoute,
  DashboardSalonsIndexRoute: DashboardSalonsIndexRoute,
  DashboardTemplatesIndexRoute: DashboardTemplatesIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  OnboardingSuccessRoute: OnboardingSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
